config/routes.rb
Qrserver::Application.routes.draw do
  get "bussoleno/index"
  get "bussoleno/new"
  get "bussoleno/export", to: 'bussoleno#export'
  get "bussoleno/:id", to: 'bussoleno#show'
  post "bussoleno/new", to: 'bussoleno#create'
  get "bussoleno/edit/:id", to: 'bussoleno#edit'
  post "bussoleno/edit/:id", to: 'bussoleno#editbussoleno'
  get "bussoleno/print/:id", to: 'bussoleno#print'
  get "bussoleno/print_small/:id", to: 'bussoleno#print_small'

  get '/badges/bussoleno', to: 'badges#bussoleno'
  post '/badges/bussoleno', to: 'badges#newbussoleno'

  resources :presences

  resources :details

  resources :badges do
  	resources :details
	resources :presences
  end

  resources :books

  resources :libraries do
  	resources :books
  end

  resources :attributes

  resources :resources do
  	resource :attributes
  end

  get '/presences/list/:id', to: 'presences#list'
  
  

root :to => 'bussoleno#index'

end

app/models/presence.rb
class Presence < ActiveRecord::Base
  belongs_to :badge
  attr_accessible :created_by, :value
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  # GET /presences
  # GET /presences.json
  def index
    if (params[:day] == nil)
	@presences = Presence.order("created_at DESC")
    else
	@presences = Presence.where(created_at: params[:day].to_i.days.ago..1.days.from_now).order(:created_at)
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @presences }
    end
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
    @presence = Presence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @presence }
    end
  end

  # GET /presences/new
  # GET /presences/new.json
  def new
    @presence = Presence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @presence }
    end
  end

  # GET /presences/1/edit
  def edit
    @presence = Presence.find(params[:id])
  end

  # POST /presences
  # POST /presences.json
  def create
    @badge = Badge.find(params[:badge_id])
    @presence = @badge.presences.build(params[:presence])
    if @presence.value == nil
    	@presence.value = 1
    end

    respond_to do |format|
      if @presence.save
#        format.html { redirect_to @presence, notice: 'Presence was successfully created.' }
        format.html { render json: @presence, status: :created, location: @presence }
        format.json { render json: @presence, status: :created, location: @presence }
      else
        format.html { render action: "new" }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /presences/1
  # PUT /presences/1.json
  def update
    @presence = Presence.find(params[:id])

    respond_to do |format|
      if @presence.update_attributes(params[:presence])
        format.html { redirect_to @presence, notice: 'Presence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1
  # DELETE /presences/1.json
  def destroy
    @presence = Presence.find(params[:id])
    @presence.destroy

    respond_to do |format|
      format.html { redirect_to presences_url }
      format.json { head :no_content }
    end
  end

  def list
    if params[:id] == 'all'
       @badges = Badge.find(:all)
    else
       # use Badge.pluck instead?
       a_badges = Array.new
       a_badges << Badge.find(params[:id])
       @badges = a_badges
    end

    render :list
  end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.erb
<%= form_for(@presence) do |f| %>
  <% if @presence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presence.errors.count, "error") %> prohibited this presence from being saved:</h2>

      <ul>
      <% @presence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_area :created_by %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :badge %><br />
    <%= f.text_field :badge %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presences/_index.html.erb
<% if presence != nil %>
    <td><%= presence.created_by %></td>
    <td><%= presence.value %></td>
    <td><%= presence.created_at %></td>
    <td>
    <%= if presence.badge != nil
            presence.badge.name
        else
            'NO NAME'
        end %>
    </td>
<% end %>

app/views/presences/edit.html.erb
<h1>Editing presence</h1>

<%= render 'form' %>

<%= link_to 'Show', @presence %> |
<%= link_to 'Back', presences_path %>

app/views/presences/index.html.erb
<h1>Listing presences</h1>


<table>
  <tr>
    <th>Created by</th>
    <th>Value</th>
    <th>Badge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @presences.each do |presence| %>
  <tr>
    <td><%= presence.badge %></td>

    <%= render partial: "index", locals:{presence:presence} %>
    <td><%= link_to 'Show', presence %></td>
    <td><%= link_to 'Edit', edit_presence_path(presence) %></td>
    <td><%= link_to 'Destroy', presence, method: :delete, data: { confirm: 'Are you sure?' } %></td>

<% end %>
</table>

<br />

<%= link_to 'New Presence', new_presence_path %>

app/views/presences/list.html.erb
<%
@badges.each do | b |
   @presences = b.presences 
%>
   
   <h2>Presences for <%= b.name %></h2>


<table>
  <tr>
    <th>Created by</th>
    <th>Value</th>
    <th>Badge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<%   @presences.each do |presence| %>
<tr>
<%=      render partial: "index", locals:{presence:presence} %>
</tr>
<%   end %>
</table>
<%end%>

app/views/presences/new.html.erb
<h1>New presence</h1>

<%= render 'form' %>

<%= link_to 'Back', presences_path %>

app/views/presences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Created by:</b>
  <%= @presence.created_by %>
</p>

<p>
  <b>Value:</b>
  <%= @presence.value %>
</p>

<p>
  <b>Badge:</b>
  <%= @presence.badge %>
</p>


<%= link_to 'Edit', edit_presence_path(@presence) %> |
<%= link_to 'Back', presences_path %>