config/routes.rb
Qrserver::Application.routes.draw do
  get "bussoleno/index"
  get "bussoleno/new"
  get "bussoleno/export", to: 'bussoleno#export'
  get "bussoleno/:id", to: 'bussoleno#show'
  post "bussoleno/new", to: 'bussoleno#create'
  get "bussoleno/edit/:id", to: 'bussoleno#edit'
  post "bussoleno/edit/:id", to: 'bussoleno#editbussoleno'
  get "bussoleno/print/:id", to: 'bussoleno#print'
  get "bussoleno/print_small/:id", to: 'bussoleno#print_small'

  get '/badges/bussoleno', to: 'badges#bussoleno'
  post '/badges/bussoleno', to: 'badges#newbussoleno'

  resources :presences

  resources :details

  resources :badges do
  	resources :details
	resources :presences
  end

  resources :books

  resources :libraries do
  	resources :books
  end

  resources :attributes

  resources :resources do
  	resource :attributes
  end

  get '/presences/list/:id', to: 'presences#list'
  
  

root :to => 'bussoleno#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
    attr_accessible :description, :name

    has_many :details
    has_many :presences
    has_many :operations

    @form_labels = {}
    @search_fields = []

    def add_detail (kind, value)
        @detail = self.details.create
        @detail.kind = kind
        @detail.value = value
        @detail.save
    end

    def add_operation (name, url, description='')
        @operation = self.operations.create
        @operation.name = name
        @operation.url = url
        @operation.description = description
        @operation.save
    end

    def self.add_search_condition(params, field)
        if params[field] != '' and params[field] != nil
            return "details.kind='#{field}' AND details.value LIKE '%#{params[field]}%'"
        else
            return nil
        end

    end

    def self.search_conditions(search_fields, params)
        conditions = Array.new

        search_fields.each do |field|
            conditions << add_search_condition(params, field)
        end
        #conditions << add_search_condition(params, :family_name)

        search_condition = conditions.compact().join(' OR ')
    end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges }
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
    @badge = Badge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @badge.to_json(:include => [:details, :presences]) }
    end
  end

  # GET /badges/new
  # GET /badges/new.json
  def new
    @badge = Badge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/1/edit
  def edit
    @badge = Badge.find(params[:id])
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(params[:badge])

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render json: @badge, status: :created, location: @badge }
      else
        format.html { render action: "new" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges/1
  # PUT /badges/1.json
  def update
    @badge = Badge.find(params[:id])

    respond_to do |format|
      if @badge.update_attributes(params[:badge])
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/bussoleno.html.erb
<h1>Nuovo Badge</h1>


<%= form_tag do %>
  <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
  <% end %>

<%= link_to 'Back', badges_path %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<% @badge.details.each do |detail| %>
<div>
<p><b><%= detail.kind %></b> <%= detail.value %></p>
</div>
<% end %>

<% @detail = @badge.details.build %>
<%= render 'details/form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>


<table class='table table-hover'>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @badges.each do |badge| %>
  <tr>
    <td><%= badge.name %></td>
    <td><%= badge.description %></td>
    <td>
    <div class="btn-group">
    <%= link_to 'Show', badge, class: 'btn btn-primary' %>
    <%= link_to 'Edit', edit_badge_path(badge), class: 'btn btn-info' %>
    <%= link_to_function 'Check In', "$.post('#{presences_path()}', {'#{:badge_id}':'#{badge.id}', '#{:presence}[#{:created_by}]':'console'})", class: 'btn btn-info' %>
    </div>
    <%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Badge', new_badge_path, class: 'btn btn-large' %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
<div class='span8'>
<h1>
  <%= @badge.name %>
</h1>
<p class="text-info">
  <%= @badge.description %>
</p>

<% @badge.details.each do |detail| %>
<div class='row'>
<div class='span2'>
<p><span class="label label-info pull-right"><%= detail.kind %></span> 
</div>
<div class='span6'>
<%= detail.value %></p>
</div>
</div>
<% end %>

</div>

<div class='span4'>
<p>
<%= image_tag "http://api.qrserver.com/v1/create-qr-code/?data=#{badge_path(@badge)}&size=250x250" %>
</p>
</div>
</div>


<% if @badge.presences != nil #FIXME %>
<h2>Presences</h2>
<% @badge.presences.each do |presence| %>
<div>
<span><%= presence.value %> on <%= presence.created_at %> by <%= presence.created_by %>
</div>
<% end %>
<% end %>



<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>