config/routes.rb
Qrserver::Application.routes.draw do
  get "bussoleno/index"
  get "bussoleno/new"
  get "bussoleno/export", to: 'bussoleno#export'
  get "bussoleno/:id", to: 'bussoleno#show'
  post "bussoleno/new", to: 'bussoleno#create'
  get "bussoleno/edit/:id", to: 'bussoleno#edit'
  post "bussoleno/edit/:id", to: 'bussoleno#editbussoleno'
  get "bussoleno/print/:id", to: 'bussoleno#print'
  get "bussoleno/print_small/:id", to: 'bussoleno#print_small'

  get '/badges/bussoleno', to: 'badges#bussoleno'
  post '/badges/bussoleno', to: 'badges#newbussoleno'

  resources :presences

  resources :details

  resources :badges do
  	resources :details
	resources :presences
  end

  resources :books

  resources :libraries do
  	resources :books
  end

  resources :attributes

  resources :resources do
  	resource :attributes
  end

  get '/presences/list/:id', to: 'presences#list'
  
  

root :to => 'bussoleno#index'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :badge
  attr_accessible :kind, :value
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # GET /details
  # GET /details.json
  def index
    @details = Detail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @details }
    end
  end

  # GET /details/1
  # GET /details/1.json
  def show
    @detail = Detail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/new
  # GET /details/new.json
  def new
    @detail = Detail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/1/edit
  def edit
    @detail = Detail.find(params[:id])
  end

  # POST /details
  # POST /details.json
  def create
    @badge = Badge.find(params[:badge_id])
    @detail = @badge.details.create(params[:detail])

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render json: @detail, status: :created, location: @detail }
      else
        format.html { render action: "new" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /details/1
  # PUT /details/1.json
  def update
    @detail = Detail.find(params[:id])
    @badge = @detail.badge

    respond_to do |format|
      if @detail.update_attributes(params[:detail])
        format.html { redirect_to edit_badge_path(@detail.badge.id), notice: 'Detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail = Detail.find(params[:id])
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for([@badge, @badge.details.build]) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<h1>Listing details</h1>

<table>
  <tr>
    <th>Kind</th>
    <th>Value</th>
    <th>Badge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @details.each do |detail| %>
  <tr>
    <td><%= detail.kind %></td>
    <td><%= detail.value %></td>
    <td><%= detail.badge %></td>
    <td><%= link_to 'Show', detail %></td>
    <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
    <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kind:</b>
  <%= @detail.kind %>
</p>

<p>
  <b>Value:</b>
  <%= @detail.value %>
</p>

<p>
  <b>Badge:</b>
  <%= @detail.badge %>
</p>


<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>